### ISSUE TITLE
Initial loading throws exception.

### ISSUE THREAD

**Issue by svparijs** [mneuhaus/Debug.Toolbar#13]
When building a clean setup my environments throws:

PHP Warning:  mkdir(): No such file or directory in /var/jenkins/jobs/1. Deploy - Development/workspace/Packages/Application/Debug.Toolbar/Classes/Debug/Toolbar/Package.php on line 17
PHP Stack trace:
PHP   1. {main}() /var/jenkins/jobs/1. Deploy - Development/workspace/flow:0
PHP   2. require() /var/jenkins/jobs/1. Deploy - Development/workspace/flow:18
PHP   3. TYPO3\Flow\Core\Bootstrap->run() /var/jenkins/jobs/1. Deploy - Development/workspace/Packages/Framework/TYPO3.Flow/Scripts/flow.php:42
PHP   4. TYPO3\Flow\Core\Booting\Scripts::initializePackageManagement() /var/jenkins/jobs/1. Deploy - Development/workspace/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Bootstrap.php:110
PHP   5. TYPO3\Flow\Package\PackageManager->initialize() /var/jenkins/jobs/1. Deploy - Development/workspace/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php:93
PHP   6. Debug\Toolbar\Package->boot() /var/jenkins/jobs/1. Deploy - Development/workspace/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageManager.php:130
PHP   7. mkdir() /var/jenkins/jobs/1. Deploy - Development/workspace/Packages/Application/Debug.Toolbar/Classes/Debug/Toolbar/Package.php:17

**Comment by mneuhaus** [comment]
could you try, if this works for you?

**Comment by svparijs** [comment]
Yes i will give it a try, ill report back to you.

**Comment by svparijs** [comment]
The issue seems to be fixed with this patch, thanks.
