### ISSUE TITLE
Exception with latest FLOW

### ISSUE THREAD

**Issue by kaystrobach** [mneuhaus/Debug.Toolbar#16]
Uncaught Exception
  Uncaught Exception
    The name of the class "AOPDebugger" is not the same as the filename
  which
    is "AopDebugger.php". Path:

  /project/Packages/Application/Debug.Toolbar/Classes/Debug/Toolbar/Debugger/AopDebugger.php

  More Information
    Exception code      #1398356897
    File  
  /project/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Object/Proxy/Compiler.php
  line 224
    Exception reference #201406021532428f3574

More Information
  Exception code      #1355480641

**Comment by mneuhaus** [comment]
hmm, weird, how did it even work before ^^.

does it work if you chante the AOPDebugger into AopDebugger in the file?

**Comment by kaystrobach** [comment]
see pull request #17
