### ISSUE TITLE
The given class "Debug\Toolbar\Debugger\AopDebugger" is not a registered   object.

### ISSUE THREAD

**Issue by cgrossde** [mneuhaus/Debug.Toolbar#8]
After downloading your package I get this error when issuing a 'flow package:list'

I use the latest Typo3 Flow (1.2 dev-master)

➜  f3m.local git:(master) ✗ flow package:list
Uncaught Exception
  The given class "Debug\Toolbar\Debugger\AopDebugger" is not a registered
  object.

More Information
  Exception code      #1245673367
  File                /Applications/MAMP/htdocs/f3m.local/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/SignalSlot/Dispatcher.php line 122
  Exception reference #201211101506198809d2

**Comment by mneuhaus** [comment]
Weird, did you try to flush the caches?

**Comment by cgrossde** [comment]
Sorry, my bad. It works now. Pretty awesome, thank you =)

**Comment by mneuhaus** [comment]
Good to hear :)

Have Fun!
